### ISSUE TITLE
Cannot connect to os1

### ISSUE THREAD

**Issue by antithing** [davemers0160/Ouster#1]
Hi, and thank you very much for making this code available. I am trying to get an os1 64 running on windows using your code, and it is giving me:

```
Log File: ../results/lidar_capture_log_20190611_204914.txt

Running lidar capture using the following parameters:
Lidar IP Address:       10.127.1.175
Config Port:            7501
Data Port:              7502
IMU Port:               7503

Receiving IP Address:   10.127.1.101
Average Capture Number: 11
Save Path:              ../results/

Configuring LIDAR: Failed!
Error Code (005): Socket connection failed. Error: -1

```

it seems the socket is wrong, but how to tell what it should be?

i am able to ping the lidar using the serial:

```
C:\Windows\system32>ping os1-************* (serial redacted)

Pinging os1-************* with 32 bytes of data:
Reply from fe80::be0f:a7ff:fe:%13: time<1ms
Reply from fe80::be0f:a7ff:fe:%13: time<1ms
Reply from fe80::be0f:a7ff:fe:%13: time<1ms
Reply from fe80::be0f:a7ff:fe:%13: time<1ms

Ping statistics for fe80::be0f:a7ff:fe:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

If you are able to help me out with this it would be very much appreciated. Thanks!

**Comment by davemers0160** [comment]
Sorry, I didn't see this until know.

If you haven't fixed it, I think that the problem is IPv4 vs IPv6.  It looks like your system is defaulting to IPv6.

Also the IP address are going to be specific to your machine and how you configure the OS-1.
